// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: proto/session.proto

package session

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoServerClient is the client API for GoServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoServerClient interface {
	GetCat(ctx context.Context, in *GetCatRequest, opts ...grpc.CallOption) (*Cat, error)
}

type goServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGoServerClient(cc grpc.ClientConnInterface) GoServerClient {
	return &goServerClient{cc}
}

func (c *goServerClient) GetCat(ctx context.Context, in *GetCatRequest, opts ...grpc.CallOption) (*Cat, error) {
	out := new(Cat)
	err := c.cc.Invoke(ctx, "/session.GoServer/GetCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoServerServer is the server API for GoServer service.
// All implementations must embed UnimplementedGoServerServer
// for forward compatibility
type GoServerServer interface {
	GetCat(context.Context, *GetCatRequest) (*Cat, error)
	mustEmbedUnimplementedGoServerServer()
}

// UnimplementedGoServerServer must be embedded to have forward compatible implementations.
type UnimplementedGoServerServer struct {
}

func (UnimplementedGoServerServer) GetCat(context.Context, *GetCatRequest) (*Cat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCat not implemented")
}
func (UnimplementedGoServerServer) mustEmbedUnimplementedGoServerServer() {}

// UnsafeGoServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoServerServer will
// result in compilation errors.
type UnsafeGoServerServer interface {
	mustEmbedUnimplementedGoServerServer()
}

func RegisterGoServerServer(s grpc.ServiceRegistrar, srv GoServerServer) {
	s.RegisterService(&GoServer_ServiceDesc, srv)
}

func _GoServer_GetCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServerServer).GetCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.GoServer/GetCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServerServer).GetCat(ctx, req.(*GetCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoServer_ServiceDesc is the grpc.ServiceDesc for GoServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.GoServer",
	HandlerType: (*GoServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCat",
			Handler:    _GoServer_GetCat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/session.proto",
}
